Hooks:PostHook(WeaponFactoryTweakData, "create_bonuses", "CAFCWMod_XxNelsonxX_Init", function(self)
if self.wpn_fps_ass_m4_beowulf then
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_fl_ass_spotter")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_fl_wml")
	self:cafcw_add_to_parts("other", "wpn_fps_ass_m4_beowulf", "wpn_fps_shield_m4")
	self:cafcw_add_to_parts("other", "wpn_fps_ass_m4_beowulf", "wpn_fps_shield_skin_ftp")
	self:cafcw_add_to_parts("other", "wpn_fps_ass_m4_beowulf", "wpn_fps_shield_skin_urban")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_fl_anpeq2")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_fl_dbal_d2")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_fl_m600p")
	self:cafcw_add_to_parts("gadget", "wpn_fps_ass_m4_beowulf", "wpn_fps_upg_fl_utg")
	self:cafcw_add_modpack("stock", "wpn_fps_ass_m4_beowulf", "AR15_StockPack")
	self:cafcw_add_modpack("stock", "wpn_fps_ass_m4_beowulf", "Stock_Attachment_Pack")
	self:cafcw_add_custom_sights("specter", "wpn_fps_ass_m4_beowulf", "wpn_fps_ass_m4")
	self:cafcw_add_custom_sights("acog", "wpn_fps_ass_m4_beowulf", "wpn_fps_ass_m4")
	self:cafcw_add_custom_sights("custom", "wpn_fps_ass_m4_beowulf", "wpn_fps_ass_m4")
	self:cafcw_add_custom_sights("rds45", "wpn_fps_ass_m4_beowulf", "wpn_fps_ass_m4")
end
end)